title: "Meng Yin"
author: "Meng Yin"
description: "Tohoku University, Sendai, Japan"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", file: "index.md", icon: home}
  - {title: "About Me", file: "aboutme.md", icon: user-circle}
  - {title: "Achievements", file: "publications.md", icon: chevron-circle-right}
  - {title: "Find My CV", file: "Meng Yin-cv.pdf", icon: file}
  - {title: "Our Lab", url: "http://www.miura.rift.mech.tohoku.ac.jp/en/home_en.html", icon: link}
  - {title: "Blog", file: "blog.md", icon: bookmark}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Send Me Mail, icon: envelope, url: "mailto:yinmeng1998@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/MengYin-ink"}
  - {title: Linkedin, icon: linkedin, url: "/feed.xml"}

#comments:
 # disqus_shortname: ""    # see https://disqus.com/
 # isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-remote-theme
 
remote_theme: niklasbuschmann/contrast@v2.11
